### ISSUE TITLE
Diagrama de Fluxo

### ISSUE THREAD

**Issue by Rsilva96** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2021-2-e2-proj-int-t2-app-help#17]
Sprint 2

**Comment by rafaelbatista3** [comment]
[Diagrama de Fluxo App HELP.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2021-2-e2-proj-int-t2-app-help/files/7158132/Diagrama.de.Fluxo.App.HELP.pdf)

**Comment by rafaelbatista3** [comment]
![Diagrama de Fluxo App HELP_page-0001](https://user-images.githubusercontent.com/84281638/133516673-7e5177ad-e299-4a23-922b-1010c9bfe2ba.jpg)
